---
version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/
# and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: ${pihole_image}
    hostname: ${SERVER_NAME}
    depends_on:
      - stubby
      - server
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "8080:80/tcp"
    environment:
      TZ: ${TZ}
      VIRTUAL_HOST: ${SERVER_NAME}
      PROXY_LOCATION: ${SERVER_NAME}
      FTLCONF_LOCAL_IPV4: ${SERVER_IP}
      WEBPASSWORD: ${PIHOLE_WEB_PASSWORD}
      PIHOLE_DNS_: '172.18.0.3#8053;172.18.0.4#5053'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    networks:
      dns:
        ipv4_address: 172.18.0.2
    restart: unless-stopped

  stubby:
    image: ${stubby_image}
    container_name: stubby
    volumes:
      - ${STUBBY_CONF}:/opt/stubby/etc/stubby/stubby.yml:ro
    networks:
      dns:
        ipv4_address: 172.18.0.3
    ports:
      - "10053:8053/udp"
    deploy:
      resources:
        limits:
          memory: 100M
    restart: unless-stopped

  server:
    image: ${dnscrypt_image}
    container_name: dnscrypt-proxy
    volumes:
      - ${DNSCRYPT_CONF}:/config/dnscrypt-proxy.toml:ro
    networks:
      dns:
        ipv4_address: 172.18.0.4
    ports:
      - "20053:5053/udp"
    deploy:
      resources:
        limits:
          memory: 100M
    restart: unless-stopped


networks:
  dns:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
#
